### ISSUE TITLE
Fix coverage <100% not failing as Travis job 

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-emailer#16]
![screenshot from 2017-01-25 10-50-36](https://cloud.githubusercontent.com/assets/546692/22285511/3b00aa80-e2ec-11e6-83cf-b0317189d7ee.png)

**Comment by Natim** [comment]
We have the exact same issue on [webpush-channels](https://github.com/webpush-channels/webpush-channels) can we have a look at it together?

**Comment by leplatrem** [comment]
I tried to reproduce here https://travis-ci.org/Kinto/kinto-emailer/builds/195184166 but couldn't.
Closing.
