### ISSUE TITLE
Add a «test send» command 

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-emailer#35]
```
$ kinto-emailer-test config/kinto.ini test@restmail.net
Email sent successfully.
```

**Comment by Natim** [comment]
How is it different from https://github.com/Kinto/kinto-emailer/pull/34 ?

**Comment by leplatrem** [comment]
The validate script in #34 is like an end-to-end script that relies on internal Kinto events etc.

This would allow OPS to just test the parameters set in the `.ini` config and make sure the app can send emails at least :)
