### ISSUE TITLE
Emails are not sent :|

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-emailer#38]
Because we plug sending notifications to `AfterResourceChanged`, we are out of the request transaction.

Because we use `get_mailer().send()`, and because *pyramid-tm* is enabled, *pyramid-emailer* is waiting for the transaction to be committed to send emails.

The solution would be to use `send_immediately(...)` instead of `send()`. Or call `transaction.commit()` but this could have side effects so I would suggest the former.

**Comment by glasserc** [comment]
Just to clarify:

> Because we use get_mailer().send(), and because pyramid-tm is enabled, pyramid-emailer is waiting for the transaction to be committed to send emails.

And this will never happen because the transaction was already committed, right?

**Comment by leplatrem** [comment]
> And this will never happen because the transaction was already committed, right?

Yes because we subscribed the `send_notifications()` listener to the `AfterResourceChanged` event — which is emitted after commit :/
